from lxml import html
import requests

# a list of parliment name and code
parlimen = [
    {"id": 1, "kod": "P001", "kawasan": "PADANG BESAR"},
    {"id": 2, "kod": "P002", "kawasan": "KANGAR"},
    {"id": 3, "kod": "P003", "kawasan": "ARAU"},
    {"id": 4, "kod": "P004", "kawasan": "LANGKAWI"},
    {"id": 5, "kod": "P005", "kawasan": "JERLUN"},
    {"id": 6, "kod": "P006", "kawasan": "KUBANG PASU"},
    {"id": 7, "kod": "P007", "kawasan": "PADANG TERAP"},
    {"id": 8, "kod": "P008", "kawasan": "POKOK SENA"},
    {"id": 9, "kod": "P009", "kawasan": "ALOR SETAR"},
    {"id": 10, "kod": "P010", "kawasan": "KUALA KEDAH"},
    {"id": 11, "kod": "P011", "kawasan": "PENDANG"},
    {"id": 12, "kod": "P012", "kawasan": "JERAI"},
    {"id": 13, "kod": "P013", "kawasan": "SIK"},
    {"id": 14, "kod": "P014", "kawasan": "MERBOK"},
    {"id": 15, "kod": "P015", "kawasan": "SUNGAI PETANI"},
    {"id": 16, "kod": "P016", "kawasan": "BALING"},
    {"id": 17, "kod": "P017", "kawasan": "PADANG SERAI"},
    {"id": 18, "kod": "P018", "kawasan": "KULIM-BANDAR BHARU"},
    {"id": 19, "kod": "P019", "kawasan": "TUMPAT"},
    {"id": 20, "kod": "P020", "kawasan": "PENGKALAN CHEPA"},
    {"id": 21, "kod": "P021", "kawasan": "KOTA BHARU"},
    {"id": 22, "kod": "P022", "kawasan": "PASIR MAS"},
    {"id": 23, "kod": "P023", "kawasan": "RANTAU PANJANG"},
    {"id": 24, "kod": "P024", "kawasan": "KUBANG KERIAN"},
    {"id": 25, "kod": "P025", "kawasan": "BACHOK"},
    {"id": 26, "kod": "P026", "kawasan": "KETEREH"},
    {"id": 27, "kod": "P027", "kawasan": "TANAH MERAH"},
    {"id": 28, "kod": "P028", "kawasan": "PASIR PUTEH"},
    {"id": 29, "kod": "P029", "kawasan": "MACHANG"},
    {"id": 30, "kod": "P030", "kawasan": "JELI"},
    {"id": 31, "kod": "P031", "kawasan": "KUALA KRAI"},
    {"id": 32, "kod": "P032", "kawasan": "GUA MUSANG"},
    {"id": 33, "kod": "P033", "kawasan": "BESUT"},
    {"id": 34, "kod": "P034", "kawasan": "SETIU"},
    {"id": 35, "kod": "P035", "kawasan": "KUALA NERUS"},
    {"id": 36, "kod": "P036", "kawasan": "KUALA TERENGGANU"},
    {"id": 37, "kod": "P037", "kawasan": "MARANG"},
    {"id": 38, "kod": "P038", "kawasan": "HULU TERENGGANU"},
    {"id": 39, "kod": "P039", "kawasan": "DUNGUN"},
    {"id": 40, "kod": "P040", "kawasan": "KEMAMAN"},
    {"id": 41, "kod": "P041", "kawasan": "KEPALA BATAS"},
    {"id": 42, "kod": "P042", "kawasan": "TASEK GELUGOR"},
    {"id": 43, "kod": "P043", "kawasan": "BAGAN"},
    {"id": 44, "kod": "P044", "kawasan": "PERMATANG PAUH"},
    {"id": 45, "kod": "P045", "kawasan": "BUKIT MERTAJAM"},
    {"id": 46, "kod": "P046", "kawasan": "BATU KAWAN"},
    {"id": 47, "kod": "P047", "kawasan": "NIBONG TEBAL"},
    {"id": 48, "kod": "P048", "kawasan": "BUKIT BENDERA"},
    {"id": 49, "kod": "P049", "kawasan": "TANJONG"},
    {"id": 50, "kod": "P050", "kawasan": "JELUTONG"},
    {"id": 51, "kod": "P051", "kawasan": "BUKIT GELUGOR"},
    {"id": 52, "kod": "P052", "kawasan": "BAYAN BARU"},
    {"id": 53, "kod": "P053", "kawasan": "BALIK PULAU"},
    {"id": 54, "kod": "P054", "kawasan": "GERIK"},
    {"id": 55, "kod": "P055", "kawasan": "LENGGONG"},
    {"id": 56, "kod": "P056", "kawasan": "LARUT"},
    {"id": 57, "kod": "P057", "kawasan": "PARIT BUNTAR"},
    {"id": 58, "kod": "P058", "kawasan": "BAGAN SERAI"},
    {"id": 59, "kod": "P059", "kawasan": "BUKIT GANTANG"},
    {"id": 60, "kod": "P060", "kawasan": "TAIPING"},
    {"id": 61, "kod": "P061", "kawasan": "PADANG RENGAS"},
    {"id": 62, "kod": "P062", "kawasan": "SUNGAI SIPUT"},
    {"id": 63, "kod": "P063", "kawasan": "TAMBUN"},
    {"id": 64, "kod": "P064", "kawasan": "IPOH TIMUR"},
    {"id": 65, "kod": "P065", "kawasan": "IPOH BARAT"},
    {"id": 66, "kod": "P066", "kawasan": "BATU GAJAH"},
    {"id": 67, "kod": "P067", "kawasan": "KUALA KANGSAR"},
    {"id": 68, "kod": "P068", "kawasan": "BERUAS"},
    {"id": 69, "kod": "P069", "kawasan": "PARIT"},
    {"id": 70, "kod": "P070", "kawasan": "KAMPAR"},
    {"id": 71, "kod": "P071", "kawasan": "GOPENG"},
    {"id": 72, "kod": "P072", "kawasan": "TAPAH"},
    {"id": 73, "kod": "P073", "kawasan": "PASIR SALAK"},
    {"id": 74, "kod": "P074", "kawasan": "LUMUT"},
    {"id": 75, "kod": "P075", "kawasan": "BAGAN DATUK"},
    {"id": 76, "kod": "P076", "kawasan": "TELUK INTAN"},
    {"id": 77, "kod": "P077", "kawasan": "TANJONG MALIM"},
    {"id": 78, "kod": "P078", "kawasan": "CAMERON HIGHLANDS"},
    {"id": 79, "kod": "P079", "kawasan": "LIPIS"},
    {"id": 80, "kod": "P080", "kawasan": "RAUB"},
    {"id": 81, "kod": "P081", "kawasan": "JERANTUT"},
    {"id": 82, "kod": "P082", "kawasan": "INDERA MAHKOTA"},
    {"id": 83, "kod": "P083", "kawasan": "KUANTAN"},
    {"id": 84, "kod": "P084", "kawasan": "PAYA BESAR"},
    {"id": 85, "kod": "P085", "kawasan": "PEKAN"},
    {"id": 86, "kod": "P086", "kawasan": "MARAN"},
    {"id": 87, "kod": "P087", "kawasan": "KUALA KRAU"},
    {"id": 88, "kod": "P088", "kawasan": "TEMERLOH"},
    {"id": 89, "kod": "P089", "kawasan": "BENTONG"},
    {"id": 90, "kod": "P090", "kawasan": "BERA"},
    {"id": 91, "kod": "P091", "kawasan": "ROMPIN"},
    {"id": 92, "kod": "P092", "kawasan": "SABAK BERNAM"},
    {"id": 93, "kod": "P093", "kawasan": "SUNGAI BESAR"},
    {"id": 94, "kod": "P094", "kawasan": "HULU SELANGOR"},
    {"id": 95, "kod": "P095", "kawasan": "TANJUNG KARANG"},
    {"id": 96, "kod": "P096", "kawasan": "KUALA SELANGOR"},
    {"id": 97, "kod": "P097", "kawasan": "SELAYANG"},
    {"id": 98, "kod": "P098", "kawasan": "GOMBAK"},
    {"id": 99, "kod": "P099", "kawasan": "AMPANG"},
    {"id": 100, "kod": "P100", "kawasan": "PANDAN"},
    {"id": 101, "kod": "P101", "kawasan": "HULU LANGAT"},
    {"id": 102, "kod": "P102", "kawasan": "BANGI"},
    {"id": 103, "kod": "P103", "kawasan": "PUCHONG"},
    {"id": 104, "kod": "P104", "kawasan": "SUBANG"},
    {"id": 105, "kod": "P105", "kawasan": "PETALING JAYA"},
    {"id": 106, "kod": "P106", "kawasan": "DAMANSARA"},
    {"id": 107, "kod": "P107", "kawasan": "SUNGAI BULOH"},
    {"id": 108, "kod": "P108", "kawasan": "SHAH ALAM"},
    {"id": 109, "kod": "P109", "kawasan": "KAPAR"},
    {"id": 110, "kod": "P110", "kawasan": "KLANG"},
    {"id": 111, "kod": "P111", "kawasan": "KOTA RAJA"},
    {"id": 112, "kod": "P112", "kawasan": "KUALA LANGAT"},
    {"id": 113, "kod": "P113", "kawasan": "SEPANG"},
    {"id": 114, "kod": "P114", "kawasan": "KEPONG"},
    {"id": 115, "kod": "P115", "kawasan": "BATU"},
    {"id": 116, "kod": "P116", "kawasan": "WANGSA MAJU"},
    {"id": 117, "kod": "P117", "kawasan": "SEGAMBUT"},
    {"id": 118, "kod": "P118", "kawasan": "SETIAWANGSA"},
    {"id": 119, "kod": "P119", "kawasan": "TITIWANGSA"},
    {"id": 120, "kod": "P120", "kawasan": "BUKIT BINTANG"},
    {"id": 121, "kod": "P121", "kawasan": "LEMBAH PANTAI"},
    {"id": 122, "kod": "P122", "kawasan": "SEPUTEH"},
    {"id": 123, "kod": "P123", "kawasan": "CHERAS"},
    {"id": 124, "kod": "P124", "kawasan": "BANDAR TUN RAZAK"},
    {"id": 125, "kod": "P125", "kawasan": "PUTRAJAYA"},
    {"id": 126, "kod": "P126", "kawasan": "JELEBU"},
    {"id": 127, "kod": "P127", "kawasan": "JEMPOL"},
    {"id": 128, "kod": "P128", "kawasan": "SEREMBAN"},
    {"id": 129, "kod": "P129", "kawasan": "KUALA PILAH"},
    {"id": 130, "kod": "P130", "kawasan": "RASAH"},
    {"id": 131, "kod": "P131", "kawasan": "REMBAU"},
    {"id": 132, "kod": "P132", "kawasan": "PORT DICKSON"},
    {"id": 133, "kod": "P133", "kawasan": "TAMPIN"},
    {"id": 134, "kod": "P134", "kawasan": "MASJID TANAH"},
    {"id": 135, "kod": "P135", "kawasan": "ALOR GAJAH"},
    {"id": 136, "kod": "P136", "kawasan": "TANGGA BATU"},
    {"id": 137, "kod": "P137", "kawasan": "HANG TUAH JAYA"},
    {"id": 138, "kod": "P138", "kawasan": "KOTA MELAKA"},
    {"id": 139, "kod": "P139", "kawasan": "JASIN"},
    {"id": 140, "kod": "P140", "kawasan": "SEGAMAT"},
    {"id": 141, "kod": "P141", "kawasan": "SEKIJANG"},
    {"id": 142, "kod": "P142", "kawasan": "LABIS"},
    {"id": 143, "kod": "P143", "kawasan": "PAGOH"},
    {"id": 144, "kod": "P144", "kawasan": "LEDANG"},
    {"id": 145, "kod": "P145", "kawasan": "BAKRI"},
    {"id": 146, "kod": "P146", "kawasan": "MUAR"},
    {"id": 147, "kod": "P147", "kawasan": "PARIT SULONG"},
    {"id": 148, "kod": "P148", "kawasan": "AYER HITAM"},
    {"id": 149, "kod": "P149", "kawasan": "SRI GADING"},
    {"id": 150, "kod": "P150", "kawasan": "BATU PAHAT"},
    {"id": 151, "kod": "P151", "kawasan": "SIMPANG RENGGAM"},
    {"id": 152, "kod": "P152", "kawasan": "KLUANG"},
    {"id": 153, "kod": "P153", "kawasan": "SEMBRONG"},
    {"id": 154, "kod": "P154", "kawasan": "MERSING"},
    {"id": 155, "kod": "P155", "kawasan": "TENGGARA"},
    {"id": 156, "kod": "P156", "kawasan": "KOTA TINGGI"},
    {"id": 157, "kod": "P157", "kawasan": "PENGERANG"},
    {"id": 158, "kod": "P158", "kawasan": "TEBRAU"},
    {"id": 159, "kod": "P159", "kawasan": "PASIR GUDANG"},
    {"id": 160, "kod": "P160", "kawasan": "JOHOR BAHRU"},
    {"id": 161, "kod": "P161", "kawasan": "PULAI"},
    {"id": 162, "kod": "P162", "kawasan": "ISKANDAR PUTERI"},
    {"id": 163, "kod": "P163", "kawasan": "KULAI"},
    {"id": 164, "kod": "P164", "kawasan": "PONTIAN"},
    {"id": 165, "kod": "P165", "kawasan": "TANJUNG PIAI"},
    {"id": 166, "kod": "P166", "kawasan": "LABUAN"},
    {"id": 167, "kod": "P167", "kawasan": "KUDAT"},
    {"id": 168, "kod": "P168", "kawasan": "KOTA MARUDU"},
    {"id": 169, "kod": "P169", "kawasan": "KOTA BELUD"},
    {"id": 170, "kod": "P170", "kawasan": "TUARAN"},
    {"id": 171, "kod": "P171", "kawasan": "SEPANGGAR"},
    {"id": 172, "kod": "P172", "kawasan": "KOTA KINABALU"},
    {"id": 173, "kod": "P173", "kawasan": "PUTATAN"},
    {"id": 174, "kod": "P174", "kawasan": "PENAMPANG"},
    {"id": 175, "kod": "P175", "kawasan": "PAPAR"},
    {"id": 176, "kod": "P176", "kawasan": "KIMANIS"},
    {"id": 177, "kod": "P177", "kawasan": "BEAUFORT"},
    {"id": 178, "kod": "P178", "kawasan": "SIPITANG"},
    {"id": 179, "kod": "P179", "kawasan": "RANAU"},
    {"id": 180, "kod": "P180", "kawasan": "KENINGAU"},
    {"id": 181, "kod": "P181", "kawasan": "TENOM"},
    {"id": 182, "kod": "P182", "kawasan": "PENSIANGAN"},
    {"id": 183, "kod": "P183", "kawasan": "BELURAN"},
    {"id": 184, "kod": "P184", "kawasan": "LIBARAN"},
    {"id": 185, "kod": "P185", "kawasan": "BATU SAPI"},
    {"id": 186, "kod": "P186", "kawasan": "SANDAKAN"},
    {"id": 187, "kod": "P187", "kawasan": "KINABATANGAN"},
    {"id": 188, "kod": "P188", "kawasan": "LAHAD DATU"},
    {"id": 189, "kod": "P189", "kawasan": "SEMPORNA"},
    {"id": 190, "kod": "P190", "kawasan": "TAWAU"},
    {"id": 191, "kod": "P191", "kawasan": "KALABAKAN"},
    {"id": 192, "kod": "P192", "kawasan": "MAS GADING"},
    {"id": 193, "kod": "P193", "kawasan": "SANTUBONG"},
    {"id": 194, "kod": "P194", "kawasan": "PETRA JAYA"},
    {"id": 195, "kod": "P195", "kawasan": "BANDAR KUCHING"},
    {"id": 196, "kod": "P196", "kawasan": "STAMPIN"},
    {"id": 197, "kod": "P197", "kawasan": "KOTA SAMARAHAN"},
    {"id": 198, "kod": "P198", "kawasan": "PUNCAK BORNEO"},
    {"id": 199, "kod": "P199", "kawasan": "SERIAN"},
    {"id": 200, "kod": "P200", "kawasan": "BATANG SADONG"},
    {"id": 201, "kod": "P201", "kawasan": "BATANG LUPAR"},
    {"id": 202, "kod": "P202", "kawasan": "SRI AMAN"},
    {"id": 203, "kod": "P203", "kawasan": "LUBOK ANTU"},
    {"id": 204, "kod": "P204", "kawasan": "BETONG"},
    {"id": 205, "kod": "P205", "kawasan": "SARATOK"},
    {"id": 206, "kod": "P206", "kawasan": "TANJONG MANIS"},
    {"id": 207, "kod": "P207", "kawasan": "IGAN"},
    {"id": 208, "kod": "P208", "kawasan": "SARIKEI"},
    {"id": 209, "kod": "P209", "kawasan": "JULAU"},
    {"id": 210, "kod": "P210", "kawasan": "KANOWIT"},
    {"id": 211, "kod": "P211", "kawasan": "LANANG"},
    {"id": 212, "kod": "P212", "kawasan": "SIBU"},
    {"id": 213, "kod": "P213", "kawasan": "MUKAH"},
    {"id": 214, "kod": "P214", "kawasan": "SELANGAU"},
    {"id": 215, "kod": "P215", "kawasan": "KAPIT"},
    {"id": 216, "kod": "P216", "kawasan": "HULU RAJANG"},
    {"id": 217, "kod": "P217", "kawasan": "BINTULU"},
    {"id": 218, "kod": "P218", "kawasan": "SIBUTI"},
    {"id": 219, "kod": "P219", "kawasan": "MIRI"},
    {"id": 220, "kod": "P220", "kawasan": "BARAM"},
    {"id": 221, "kod": "P221", "kawasan": "LIMBANG"},
    {"id": 222, "kod": "P222", "kawasan": "LAWAS"},
]

page = requests.get("https://www.parlimen.gov.my/ahli-dewan.html?uweb=dr&")
tree = html.fromstring(page.content)

# Create a list of wakil rakyat names
nama_wakil_rakyat = tree.xpath(
    '//li/div/a[following-sibling::div[@class="constituency"]]/div/span[@class="first-name"]/text()'
)
kod = tree.xpath('//div[@class="constituency"]/text()')
parti = tree.xpath('//div[@class="caucus"]/text()')
kawasan = tree.xpath(
    '//div[@class="province"][preceding-sibling::div[@class="caucus"]]/text()'
)

wakil_rakyat_parlimen = []

for (nama, kd, p, kw) in zip(nama_wakil_rakyat, kod, parti, kawasan):
    kod_id = int(kd.replace("P", ""))
    wakil_rakyat_parlimen.append(
        {
            "id": kod_id,
            "kod": kd,
            "kawasan": kw,
            "nama_wakil_rakyat": nama,
            "parti": p,
        }
    )

# Check for empty parliment seats
available_ids = [i["id"] for i in wakil_rakyat_parlimen]
for i in range(1, 223):
    if i not in available_ids:
        not_available_parlimen = [p for p in parlimen if p["id"] == i][0]
        not_available_parlimen["nama_wakil_rakyat"] = "Tiada"
        not_available_parlimen["parti"] = "Tiada"
        wakil_rakyat_parlimen.append(not_available_parlimen)

wakil_rakyat_parlimen = sorted(wakil_rakyat_parlimen, key=lambda i: i["id"])

file = open("data.py", "w")
file.write("%s = %s\n" % ("wakil_rakyat_parlimen", wakil_rakyat_parlimen))
file.close()

# print(wakil_rakyat_parlimen)
